// Copyright 2023 The Toucan Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <api.h>  // generated by generate_bindings

#include <assert.h>
#include <stdio.h>

#include <memory>
#include <string.h>

#include <jpeglib.h>
#include <ultrahdr_api.h>

#include <ast/type.h>

namespace Toucan {

struct Image {
  Type*                         pixelFormat;
  struct jpeg_decompress_struct cinfo;
  struct jpeg_error_mgr         jerr;
  uint32_t                      size[2];
  Object                        encodedImage;
};

namespace {
void AssertSupportedPixelFormat(Type* pixelFormat) {
  assert(pixelFormat->IsClass());
  auto classType = static_cast<ClassType*>(pixelFormat);
  auto parent = classType->GetParent();
  assert(parent->GetName() == "PixelFormat");
  auto templateArgs = parent->GetTemplateArgs();
  assert(templateArgs.size() == 2);
}
}  // namespace

Image* Image_Image(int qualifiers, Type* pixelFormat, Object* encodedImage) {
  if (!encodedImage->ptr) return nullptr; 
  uint32_t length = encodedImage->controlBlock->arrayLength;
  auto     result = new Image();
  result->pixelFormat = pixelFormat;
  result->encodedImage = *encodedImage;
  result->encodedImage.controlBlock->strongRefs++;
  result->encodedImage.controlBlock->weakRefs++;
  AssertSupportedPixelFormat(pixelFormat);
  result->cinfo.err = jpeg_std_error(&result->jerr);
  jpeg_create_decompress(&result->cinfo);
  jpeg_mem_src(&result->cinfo, static_cast<unsigned char*>(encodedImage->ptr), length);
  jpeg_read_header(&result->cinfo, TRUE);
  result->size[0] = result->cinfo.image_width;
  result->size[1] = result->cinfo.image_height;
  return result;
}

const uint32_t* Image_GetSize(Image* This) { return This->size; }

void Image_Decode(Image* This, Array* dest, uint32_t bufferWidth) {
  auto pixelFormatName = static_cast<ClassType*>(This->pixelFormat)->GetName();
  if (pixelFormatName == "RGBA16float") {
    uhdr_compressed_image_t compressed_img;
    compressed_img.data = This->encodedImage.ptr;
    compressed_img.data_sz = This->encodedImage.controlBlock->arrayLength;
    compressed_img.capacity = This->encodedImage.controlBlock->arrayLength;
    compressed_img.cg = UHDR_CG_UNSPECIFIED;
    compressed_img.ct = UHDR_CT_UNSPECIFIED;
    compressed_img.range = UHDR_CR_UNSPECIFIED;

    uhdr_codec_private_t* dec = uhdr_create_decoder();
    if (!dec) {
      assert(!"failed to create ultrahdr decoder");
      return;
    }
    uhdr_dec_set_image(dec, &compressed_img);
    uhdr_dec_set_out_img_format(dec, UHDR_IMG_FMT_64bppRGBAHalfFloat);

    uhdr_error_info_t err = uhdr_decode(dec);
   if (err.error_code != UHDR_CODEC_OK) {
      assert(!"failed to decode ultrahdr image");
      uhdr_release_decoder(dec);
      return;
    }

    uhdr_raw_image_t* raw_img = uhdr_get_decoded_image(dec);
   if (!raw_img || raw_img->fmt != UHDR_IMG_FMT_64bppRGBAHalfFloat) {
      assert(!"failed to get decoded ultrahdr image or unexpected format");
      uhdr_release_decoder(dec);
      return;
    }

    uint16_t* src_ptr = static_cast<uint16_t*>(raw_img->planes[UHDR_PLANE_PACKED]);
    uint16_t* dest_ptr = static_cast<uint16_t*>(dest->ptr);
    unsigned int src_stride_pixels = raw_img->stride[UHDR_PLANE_PACKED];
    unsigned int width = raw_img->w;
    unsigned int height = raw_img->h;

    for (unsigned int y = 0; y < height; ++y) {
      uint16_t* src_row = src_ptr + y * src_stride_pixels * 4;
      uint16_t* dest_row = dest_ptr + y * bufferWidth * 4;
      memcpy(dest_row, src_row, width * 8); // 8 bytes per pixel (4 channels * 16-bit)
    }
    uhdr_release_decoder(dec);
    return; 
  }
  jpeg_start_decompress(&This->cinfo);
  uint32_t* p = static_cast<uint32_t*>(dest->ptr);

  int        row_stride = This->cinfo.output_width * This->cinfo.output_components;
  JSAMPARRAY scanline = (*This->cinfo.mem->alloc_sarray)(
      reinterpret_cast<j_common_ptr>(&This->cinfo), JPOOL_IMAGE, row_stride, 1);
  uint32_t rshift = 0;
  uint32_t gshift = 8;
  uint32_t bshift = 16;
  if (static_cast<ClassType*>(This->pixelFormat)->GetName() == "BGRA8unorm") {
    rshift = 16;
    bshift = 0;
  }
  while (This->cinfo.output_scanline < This->cinfo.output_height) {
    jpeg_read_scanlines(&This->cinfo, scanline, 1);
    if (This->cinfo.output_components == 3) {
      uint8_t* buf = scanline[0];
      for (int x = 0; x < This->size[0]; x++) {
        uint8_t r = *buf++;
        uint8_t g = *buf++;
        uint8_t b = *buf++;
        p[x] = 0xFF000000 | r << rshift | g << gshift | b << bshift;
      }
    } else if (This->cinfo.output_components == 1) {
      uint8_t* buf = scanline[0];
      for (int x = 0; x < This->size[0]; x++) {
        uint8_t r = *buf++;
        p[x] = 0xFF000000 | r << rshift | r << gshift | r << bshift;
      }
    } else {
      assert(!"unsupported jpeg component count");
    }
    p += bufferWidth;
  }
  jpeg_finish_decompress(&This->cinfo);
}

void Image_Destroy(Image* This) {
  // FIXME: make wrappers create Toucan null for native null
  if (This == nullptr) return;

  jpeg_destroy_decompress(&This->cinfo);
  This->encodedImage.controlBlock->strongRefs--;
  if (This->encodedImage.controlBlock->strongRefs == 0) {
    free(This->encodedImage.ptr);
  }
  This->encodedImage.controlBlock->weakRefs--;
  if (This->encodedImage.controlBlock->weakRefs == 0) {
    free(This->encodedImage.controlBlock);
  }
  delete This;
}

};  // namespace Toucan
